Add support for providing the URL to the cloudformation template file, instead of the script coping it to the S3 bucket.

diff --git a/FSx_Alerting/FSx_ONTAP_Alerting/deployStack b/FSx_Alerting/FSx_ONTAP_Alerting/deployStack
--- a/FSx_Alerting/FSx_ONTAP_Alerting/deployStack
+++ b/FSx_Alerting/FSx_ONTAP_Alerting/deployStack
@@ -9,7 +9,7 @@
 ################################################################################
 usage () {
   cat <<EOF >&2
-Usage: $(basename $0) -o <ontapServer> [-R region] -b <bucket> -s <subnets> -g <securityGroup> -t <snsTopicArn> -a <secretArn> [-c <matchingConditionsFile>] [-r <roleArn>] [-i <accountId>] [-w <true|false>] [-x <watchdogRoleArn>] [-v checkInterval] [-l <lambdaLayerArn>] [-W webhookEndpoint]
+Usage: $(basename $0) -o <ontapServer> [-R region] -b <bucket> -s <subnets> -g <securityGroup> -t <snsTopicArn> -a <secretArn> [-c <matchingConditionsFile>] [-r <roleArn>] [-i <accountId>] [-w <true|false>] [-x <watchdogRoleArn>] [-v checkInterval] [-l <lambdaLayerArn>] [-W webhookEndpoint] [-f cloudformationUrl]
     -o <ontapServer> The name of the ONTAP system to monitor
     -R <region> The AWS region where the AWS resources are located. Optional, defaults to the region configured in the AWS CLI.
     -b <bucket> The S3 bucket where the CloudFormation template is stored
@@ -25,6 +25,7 @@ Usage: $(basename $0) -o <ontapServer> [-R region] -b <bucket> -s <subnets> -g <
     -v <checkInterval> The interval in minutes to check the ONTAP system (optional, the default is 15 minutes).
     -l <lambdaLayerArn> The ARN of the Lambda layer to use (optional).
     -W <webhookEndpoint> The endpoint to send notifications to (optional).
+    -f <cloudformationUrl> The URL of the CloudFormation template (optional). Should be in the form of: https://s3.<AWSregion>.amazonaws.com/<bucketName>/cloudformation.yaml
 EOF
   exit 1
 }
@@ -41,7 +42,7 @@ if [ -z "$region" ]; then
   region="$AWS_DEFAULT_REGION"
 fi
 
-while getopts "ho:b:s:g:t:a:c:i:r:w:x:v:l:R:W:" opt; do
+while getopts "ho:b:s:g:t:a:c:i:r:w:x:v:l:R:W:f:" opt; do
   case $opt in
     o) ontapServer="$OPTARG" ;;
     b) bucket="$OPTARG" ;;
@@ -58,6 +59,7 @@ while getopts "ho:b:s:g:t:a:c:i:r:w:x:v:l:R:W:" opt; do
     l) lambdaLayerArn="$OPTARG" ;;
     R) region="$OPTARG" ;;
     W) webhookEndpoint="$OPTARG" ;;
+    f) cloudformationUrl="$OPTARG" ;;
     *) usage ;;
   esac
 done
@@ -91,12 +93,14 @@ if [ ! -z "$matchingConditionsFile" ]; then
 fi
 #
 # The script got too big now it has to be stored in a S3 bucket.
-if aws s3 --region $region cp cloudformation.yaml s3://$bucket; then
-  :
-else
-  echo "Error, could not copy cloudformation.yaml to S3 bucket." >&2
-  echo "Exiting..." >&2
-  exit 1
+if [ -z "$cloudformationUrl" ]; then
+  if aws s3 --region $region cp cloudformation.yaml s3://$bucket; then
+    cloudformationUrl="https://s3.${region}.amazonaws.com/${bucket}/cloudformation.yaml"
+  else
+    echo "Error, could not copy cloudformation.yaml to S3 bucket." >&2
+    echo "Exiting..." >&2
+    exit 1
+  fi
 fi
 #
 # Since the only reason to provide a watchdog role ARN is to attach it to the Lambda function
@@ -109,7 +113,7 @@ else
 fi
 #
 # Deploy the stack
-aws cloudformation create-stack --region $region --stack-name $stackName --template-url https://s3.${region}.amazonaws.com/${bucket}/cloudformation.yaml \
+aws cloudformation create-stack --region $region --stack-name $stackName --template-url $cloudformationUrl \
   --capabilities CAPABILITY_NAMED_IAM --parameters \
   ParameterKey=OntapAdminSever,ParameterValue=$ontapServer \
   ParameterKey=subNetIds,ParameterValue="$subnets" \
