Fixed a bug where it required the -a option when it wasn't needed.

diff --git a/FSx_Alerting/FSx_ONTAP_Alerting/deployStack b/FSx_Alerting/FSx_ONTAP_Alerting/deployStack
--- a/FSx_Alerting/FSx_ONTAP_Alerting/deployStack
+++ b/FSx_Alerting/FSx_ONTAP_Alerting/deployStack
@@ -9,14 +9,14 @@
 ################################################################################
 usage () {
   cat <<EOF >&2
-Usage: $(basename $0) [-R Region>] -b <s3Bucket> -F <FSxNListFilename> -s <subnets> -g <securityGroup> -t <snsTopicArn> -a <secretArnPattern> [-v <checkInterval>] [-w <true|false>] [-r <monitoringRoleArn>] [-x <controlRoleArn>] [-l <lambdaLayerArn>] [-m maxRunTime] [-M memorySize] [-f <cloudformationUrl>]
+Usage: $(basename $0) [-R Region>] -b <s3Bucket> -F <FSxNListFilename> -s <subnets> -g <securityGroup> -t <snsTopicArn> [-a <secretArnPattern>] [-v <checkInterval>] [-w <true|false>] [-r <monitoringRoleArn>] [-x <controlRoleArn>] [-l <lambdaLayerArn>] [-m maxRunTime] [-M memorySize] [-f <cloudformationUrl>]
     -R <region> The AWS region where the AWS resources are located. Optional, defaults to the region configured in the AWS CLI.
     -b <bucket> The S3 bucket where the CloudFormation template is stored
     -F <FSxNListFilename> The name of the file in the S3 bucket that containing the list of FSxN systems to monitor.
     -s <subnets> Comma-separated list of subnet IDs (not ARNs).
     -g <securityGroup> The security group ID to use (not ARN). Just needs to allow outbound over TCP port 443.
     -t <snsTopicArn> The ARN of the SNS topic for notifications.
-    -a <secretArnPattern> The secrets ARN pattern that will match all the serects that the monitoring function will use to for FSxN credentials.
+    -a <secretArnPattern> The secrets ARN pattern that will match all the serects that the monitoring function will use to for FSxN credentials. Optional if you are providing a monitoring role.
     -v <checkInterval> The interval in minutes to check the ONTAP system (optional, the default is 15 minutes).
     -w <true|false> Create CloudWatch watchdog alarms (optional, default is true).
     -r <moniotoringRoleArn> The Arn of the role to use for the Monitoring Lambda function (optional).
@@ -69,9 +69,22 @@ while getopts "hR:b:F:S:s:g:t:a:v:w:r:x:l:W:m:M:f:" opt; do
     *) usage ;;
   esac
 done
+#
+# Check that the required arguments are provided.
+missingArgs="false"
+for var in FSxNListFilename bucket subnets securityGroup snsTopicArn; do
+  if [ -z "${!var}" ]; then
+    echo "Error: Missing required argument: $var" >&2
+    missingArgs="true"
+  fi
+done
 
-if [ -z "$FSxNListFilename" -o -z "$bucket" -o -z "$subnets" -o -z "$securityGroup" -o -z "$snsTopicArn" -o -z "$secretArnPattern" ]; then
-  echo "Error: Missing required arguments." >&2
+if [ -z "$secretArnPattern" -a -z "$monitoringRoleArn" ]; then
+  echo "Error: If not providing a monitoring role via the -r option, you must provide the secretArnPattern option." >&2
+  missingArgs="true"
+fi
+
+if [ "$missingArgs" == "true" ]; then
   usage
 fi
 
